package(
    default_visibility = [
        "//visibility:public",
    ],
    licenses = ["notice"],
)

cc_library(
    name = "onednn_util",
    hdrs = ["onednn_util.h"],
    deps = [
        "@onednn_gpu//:onednn_gpu",
        "@tsl//tsl/platform:errors",
        "@tsl//tsl/platform:logging",
    ],
)
